#include<stdio.h>
#include<stdint.h>
#include<stdlib.h>
#include<unistd.h>
#include<linux/kernel.h>
#include<sys/syscall.h>
#include<asm-generic/errno.h>


int main()
{
	uint32_t i,a;
	int32_t buffer_size = 256;
	int32_t *usort_array = NULL;
	int32_t *sort_array = NULL;
	usort_array = (int32_t*)malloc(4*buffer_size);
	if(usort_array == NULL)
	{	
		perror("Malloc failed in allocating memory\n");
	}
	sort_array = (int32_t*)malloc(4*buffer_size);
	if(sort_array == NULL)
	{	
		perror("Malloc failed in allocating memory\n");
	}
	printf("\nUnSorted Array generated by rand() function \n");
	for(i=0;i<buffer_size;i++)
	{
		*(usort_array+i)= rand() % 1000;
		printf("%d \t ",*(usort_array+i));
	}
	
	a=syscall(333,usort_array,sort_array,buffer_size);
	if(a!=0)
	printf("Error in System call execution to invalid input parameters\n");

	printf("\n*****Sorted Array from System Call***** \n");
	
	for(i=0;i<buffer_size;i++)
	{
		printf("%d \t",*(sort_array+i));
	}
	
	free(sort_array);
	free(usort_array);
	
	//call system call with null pointer
	return 0;
}
